export const ORIGINATES_FROM = ["INTRUSION-SET", "THREAT-ACTOR", "CAMPAIGN", "MALWARE"];
export const SOPHISTICATION = ["INTRUSION-SET" ,"THREAT-ACTOR", "CAMPAIGN"];
export const FIRST_SEEN = [
    "INTRUSION-SET",
    "TOOL",
    "MALWARE",
    "CAMPAIGN",
    "THREAT-ACTOR",
    "VULNERABILITY",
    // "REPORT",
];
export const LAST_SEEN = [
    "INTRUSION-SET",
    "TOOL",
    "MALWARE",
    "CAMPAIGN",
    "THREAT-ACTOR",
    "VULNERABILITY",
    // "REPORT",
];
export const PRIMARY_MOTIVATION = ["INTRUSION-SET" ,"THREAT-ACTOR", "CAMPAIGN"];
export const SECONDARY_MOTIVATION = ["INTRUSION-SET","THREAT-ACTOR", "CAMPAIGN"];
export const THREAT_ACTOR_TYPE = ["THREAT-ACTOR"]
export const TAGS = ["INTRUSION-SET", "TOOL", "MALWARE", "CAMPAIGN","REPORT","VULNERABILITY" ,"THREAT-ACTOR"];
export const TECHNIQUES = ["INTRUSION-SET", "TOOL", "MALWARE", "CAMPAIGN","REPORT","VULNERABILITY"];
export const LOCATED_AT = ["INTRUSION-SET", "THREAT-ACTOR"];
export const TARGETS = ["INTRUSION-SET", "THREAT-ACTOR", "CAMPAIGN", "MALWARE"];
export const ATTRIBUTIONS = ["INTRUSION-SET", "TOOL", "MALWARE", "CAMPAIGN","THREAT-ACTOR"];
export const DOMAINS = ["INTRUSION-SET", "TOOL", "MALWARE", "CAMPAIGN","THREAT-ACTOR"];
export const PLATFORMS = ["MALWARE"];
export const ALLIESES = ["INTRUSION-SET", "TOOL", "MALWARE", "CAMPAIGN" ,"THREAT-ACTOR"] ;
export const CVSS3SCORE = ["VULNERABILITY"];
export const POC_EXIST = ["VULNERABILITY"];
export const POC_LINK = ["VULNERABILITY"];
export const PRODUCTIONIZED = ["VULNERABILITY"];
export const PRODUCTION_LINK = ["VULNERABILITY"];
// export const RISKLEVEL = ["VULNERABILITY"];
export const PATCH = ["VULNERABILITY"];
export const PATCH_LINK = ["VULNERABILITY"];
export const UNDER_ACTIVITY_OBSERVE = ["VULNERABILITY"];
export const UNDER_ACTIVITY_LINK = ["VULNERABILITY"];
export const VENDOR = ["VULNERABILITY"];
export const PRODUCT = ["VULNERABILITY"];
export const REPORT_LIST = ["REPORT"];
export const VARIANT = ["MALWARE"];
export const Version = ["MALWARE", "TOOL"];
export const AFFECTED_PLATFORM = ["MALWARE", "TOOL"];
export const CAPABILITIES = ["MALWARE", "TOOL"];